config/routes.rb
Urlshort::Application.routes.draw do
  resources :shorts
  root to: 'shorts#new'
  match "new", to: 'shorts#new'
  match "*shorturl", to: 'shorts#xurl'

end

app/models/short.rb
class Short < ActiveRecord::Base
  attr_accessible :visits, :url, :shorturl
  #before_save :presave
  validates :url, presence: true

  #def presave
  #  self.visits = 0
  #  self.shorturl = (0...4).map{(65+rand(26)).chr}.join.downcase!
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shorts_controller.rb
class ShortsController < ApplicationController
  def new
    @link=Short.new
  end

  def create
    @link=Short.new(params[:short])
    @link.visits = 0
    @link.shorturl = (0...4).map{(65+rand(26)).chr}.join.downcase!
    if @link.save
      flash[:success] = "Link Shortened!"
      redirect_to @link
    else
      flash[:warn] = "Failed"
      render 'new'
    end
  end

  def index

  end

  def show
    @link=Short.find_by_id(params[:id])  
  end

  def xurl
    if params[:shorturl]
      @short = Short.find_by_shorturl(params[:shorturl])
      @short.visits += 1
      @short.save
      redirect_to "http://#{@short.url}"
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorts_helper.rb
module ShortsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>URLShortener</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class= "container">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
		<p><%= debug(params) if Rails.env.development? %></p>
		<div class="footer">
			<div class="container">
				<ul>
					<li>By Jeffrey Tong</li>
					<li><a href="http://jefftong.net">Site</a></li>
				</ul>
			</div>
		</div>
	</div>
</body>
</html>

app/views/shorts/_form.html.erb
<%= form_for (@link) do |f| %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <p><%= f.submit "Shorten Link!"%></p>
<%end%>

app/views/shorts/index.html.erb
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <title>ShortYourLink</title>
</head>
<body>
<h1>Welcome</h1>
<%= link_to "new link", new_short_path%>
</body>
</html>

app/views/shorts/new.html.erb
<h1>Shorten Your URL!</h1>
<%= render 'form' %>

app/views/shorts/show.html.erb
<h1>Link Analytics Page</h1>
<h5>Full URL:</h5> <%= link_to "#{@link.url}", "http://#{@link.url}" %>
<h5>Short URL:</h5> http://localhost:3000/<%= @link.shorturl %>
<h5>Number of Vists:</h5> <%= @link.visits %>